baseUrl: http://toolbox.buwa.nl
languageCode: en
title: Toolbox
theme: company-toolbox
disableKinds:
  - taxonomyTerm
  - taxonomy
  - sitemap
  - RSS
outputs:
  home:
    - html
  section:
    - json
  page:
    - json
    - html
logo: logo-waardenburg.png
params:
  logo: logo-waardenburg.png
  resources: []
