hugover: extended_0.101.0
serve:
  - key: default
    config: config.yaml
build:
  - key: default
    config: config.yaml
menu:
  - key: settings
    title: Settings
    menuItems:
      - key: mainConfig
      - key: categories
      - key: images

collections:
- dataformat: yaml
  extension: md
  folder: content/category/
  itemtitle: Category
  key: categories
  title: Categories
  fields:
  - key: title
    title: Title
    type: string
  - key: description
    title: Description
    type: string
    multiLine: true

  - key: image
    buttonTitle: select image
    path: /static/images
    title: Image
    type: image-select

  - key: resource_links
    title: Resources
    type: accordion
    fields:

    - arrayTitle: true
      key: title
      title: Title
      type: string

    - key: description
      title: Description
      type: string
      multiLine: true

    - key: image
      buttonTitle: select image
      path: /static/images
      title: Image
      type: image-select

    - key: actions
      title: Actions
      type: accordion
      fields:

      - key: info
        type: info
        content: Only the first 3 items are used. 1st action is primary
        size: small

      - arrayTitle: true
        key: title
        title: Title
        type: string

      - key: url
        title: url
        type: string

singles:

  - key: images
    description: global images
    _mergePartial: https://raw.githubusercontent.com/quiqr/model-partials/main/singles/global-images.yml

  - key: mainConfig
    title: Site Configuration
    file: config.yaml
    fields:
      - key: title
        title: Site Title
        type: string
        tip: Your page title.
      - key: baseUrl
        title: Base URL
        type: string
        tip: Your site URL.

      - key: logo
        buttonTitle: select image
        path: /static/images
        title: Logo
        type: image-select

      - key: "favicon"
        title: "Favicon Image"
        type: "bundle-manager"
        tip: "upload the image to be used as favicon"
        path: "/static/"
        forceFileName: "favicon.png"
        extensions: ["png"]

